apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-agent
  template:
    metadata:
      labels:
        app: sre-agent
    spec:
      serviceAccountName: sre-agent-sa
      containers:
      - name: agent
        # 关键：必须写完整镜像名 localhost/sre-agent:v1.0
        image: localhost/sre-agent:v1.0
        imagePullPolicy: Never  # 必须保留，使用本地镜像
